apiVersion: apps/v1
kind: Deployment
metadata:
  name: dias-manager
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dias-manager
  template:
    metadata:
      labels:
        app: dias-manager
    spec:
      containers:
      - name: manager
        image: manager:latest # container register
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dias-manager-svc
  labels:
    app: dias-manager
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30080
  selector:
    app: dias-manager
