apiVersion: apps/v1
kind: Deployment
metadata:
  name: dias-worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dias-worker
  template:
    metadata:
      labels:
        app: dias-worker
    spec:
      containers:
      - name: worker
        image: gcr.io/stately-vector-311213/worker:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dias-worker-svc
  labels:
    app: dias-worker
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30081
  selector:
    app: dias-worker
