version: "3.9"

services:
  worker:
    build: .
    image: "dias"
    hostname: worker
    volumes:
      - ../worker:/app
    container_name: worker

  manager:
    image: "dias"
    ports:
      - "8001:80"
    volumes:
      - ../manager:/app
    container_name: manager
    depends_on:
      - worker
